### ISSUE TITLE
[iOS] 1차 PR 수정 

### ISSUE THREAD

**Issue by eeeesong** [ghojeong/sidedish#30]
[0422 PR](https://github.com/codesquad-members-2021/sidedish/pull/14)의 피드백 반영하기

### 수정사항
- [x] SideDish: Class vs. Struct, var -> let
- [x] NetworkManager: Mock 객체 초기화 시에도 url 외부 주입, URLSession 부분 수정
- [x] MainViewController: bind를 private하게, Cold Observable 문제
- [x] MenuCellViewModel: print문 제거 -> 사용자에게 문제 상황 알리기
- [ ] MainTableViewDataSource: cell 이름 static 상수로 변경, `!` 제거
- [x] MainTableViewDelegate: headerView 분리하여 생성, 높이 값 상수로 저장

**Comment by Settpark** [comment]
- [x] MenuCellViewModel: print문 제거 -> 사용자에게 문제 상황 알리기
![simulator_screenshot_88F4EECB-FBFE-4443-8A44-D2FB1A0CC531](https://user-images.githubusercontent.com/64049682/115797036-ed6ff680-a40d-11eb-8ed4-b0e1f18bd008.png)

**Comment by Settpark** [comment]
- [ ] MainTableViewDataSource: cell 이름 static 상수로 변경, `!` 제거
해당 항목은 백엔드 서버의 api를 사용하면서 개선해보는 것은 어떨까요??
